LOGTALKHOME=/opt/local/share/logtalk
LOGTALKUSER=/Users/dtreacy/logtalk
PATH=$PATH:$LOGTALKHOME/tools/lgtdoc/xml:$LOGTALKHOME/scripts:$LOGTALKHOME/integration
MANPATH=$MANPATH:$LOGTALKHOME/man
export LOGTALKHOME LOGTALKUSER PATH MANPATH
